services:
  app:
    build: ./app
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app           

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
    - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: